
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.190.132:3306/greeting?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: greeting
    password: LEbRaa8ENRatXyrT




mybatis:
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 8080
  context-path: /parent001
